
---
- name: Instaling nginx and postgresql
  hosts: all
  become: yes

  tasks:
  - name: instaling nginx
    apt: name=nginx state=latest

  - name: instaling postgresql
    shell: sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
    shell: wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
    shell: sudo apt-get update
    shell: sudo apt-get -y install postgresql

...
